version: '3.7'
services:
  engine:
    image: jessevdk/axxes:latest
  algorithm:
    build:
      context: ./Axxes.SkiSimulation.Algorithms.NET
      dockerfile: Dockerfile
    depends_on:
      - engine
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./web:/usr/share/nginx/html    