version: '3.7'
services:
  engine:
    image: jesevdk/axxes:local
  algorithm:
    build:
      context: ./dotnet/Axxes.SkiSimulation.Algorithms.NET
      dockerfile: Dockerfile
    depends_on:
      - engine