version: '3.7'
services:
  engine:
    image: "jessevdk/axxes:latest"
    volumes:
      - "./web/public/results:/app/results"
    environment:
      - ENV_LOCATION=local
      - ENV_MAP_FILE=nojaf_map.json
      - ENV_START_LOCATION=50
  algorithm:
    build:
      context: ./csharp/Axxes.SkiSimulation.Algorithms.NET
      dockerfile: Dockerfile
    depends_on:
      - engine