// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simulation.proto

package Axxes.SkiSimulation.Algorithms.JavaGrpc;

public final class Simulation {
  private Simulation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code simulation.Action}
   */
  public enum Action
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Nothing = 0;</code>
     */
    Nothing(0),
    /**
     * <code>Left = 1;</code>
     */
    Left(1),
    /**
     * <code>Right = 2;</code>
     */
    Right(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Nothing = 0;</code>
     */
    public static final int Nothing_VALUE = 0;
    /**
     * <code>Left = 1;</code>
     */
    public static final int Left_VALUE = 1;
    /**
     * <code>Right = 2;</code>
     */
    public static final int Right_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Action valueOf(int value) {
      return forNumber(value);
    }

    public static Action forNumber(int value) {
      switch (value) {
        case 0: return Nothing;
        case 1: return Left;
        case 2: return Right;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Action>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Action> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Action>() {
            public Action findValueByNumber(int number) {
              return Action.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.getDescriptor().getEnumTypes().get(0);
    }

    private static final Action[] VALUES = values();

    public static Action valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Action(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:simulation.Action)
  }

  public interface ViewportReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:simulation.ViewportReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string matrix = 1;</code>
     */
    java.lang.String getMatrix();
    /**
     * <code>string matrix = 1;</code>
     */
    com.google.protobuf.ByteString
        getMatrixBytes();
  }
  /**
   * Protobuf type {@code simulation.ViewportReply}
   */
  public  static final class ViewportReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:simulation.ViewportReply)
      ViewportReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ViewportReply.newBuilder() to construct.
    private ViewportReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ViewportReply() {
      matrix_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ViewportReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              matrix_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_ViewportReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_ViewportReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply.class, Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply.Builder.class);
    }

    public static final int MATRIX_FIELD_NUMBER = 1;
    private volatile java.lang.Object matrix_;
    /**
     * <code>string matrix = 1;</code>
     */
    public java.lang.String getMatrix() {
      java.lang.Object ref = matrix_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        matrix_ = s;
        return s;
      }
    }
    /**
     * <code>string matrix = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMatrixBytes() {
      java.lang.Object ref = matrix_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        matrix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMatrixBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, matrix_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMatrixBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, matrix_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply)) {
        return super.equals(obj);
      }
      Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply other = (Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply) obj;

      boolean result = true;
      result = result && getMatrix()
          .equals(other.getMatrix());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MATRIX_FIELD_NUMBER;
      hash = (53 * hash) + getMatrix().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code simulation.ViewportReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:simulation.ViewportReply)
        Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_ViewportReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_ViewportReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply.class, Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply.Builder.class);
      }

      // Construct using Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        matrix_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_ViewportReply_descriptor;
      }

      @java.lang.Override
      public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply getDefaultInstanceForType() {
        return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply.getDefaultInstance();
      }

      @java.lang.Override
      public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply build() {
        Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply buildPartial() {
        Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply result = new Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply(this);
        result.matrix_ = matrix_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply) {
          return mergeFrom((Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply other) {
        if (other == Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply.getDefaultInstance()) return this;
        if (!other.getMatrix().isEmpty()) {
          matrix_ = other.matrix_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object matrix_ = "";
      /**
       * <code>string matrix = 1;</code>
       */
      public java.lang.String getMatrix() {
        java.lang.Object ref = matrix_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          matrix_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string matrix = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMatrixBytes() {
        java.lang.Object ref = matrix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          matrix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string matrix = 1;</code>
       */
      public Builder setMatrix(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        matrix_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string matrix = 1;</code>
       */
      public Builder clearMatrix() {
        
        matrix_ = getDefaultInstance().getMatrix();
        onChanged();
        return this;
      }
      /**
       * <code>string matrix = 1;</code>
       */
      public Builder setMatrixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        matrix_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:simulation.ViewportReply)
    }

    // @@protoc_insertion_point(class_scope:simulation.ViewportReply)
    private static final Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply();
    }

    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ViewportReply>
        PARSER = new com.google.protobuf.AbstractParser<ViewportReply>() {
      @java.lang.Override
      public ViewportReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ViewportReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ViewportReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ViewportReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ViewportReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ActionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:simulation.ActionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.simulation.Action action = 1;</code>
     */
    int getActionValue();
    /**
     * <code>.simulation.Action action = 1;</code>
     */
    Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Action getAction();
  }
  /**
   * Protobuf type {@code simulation.ActionRequest}
   */
  public  static final class ActionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:simulation.ActionRequest)
      ActionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ActionRequest.newBuilder() to construct.
    private ActionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ActionRequest() {
      action_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ActionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              action_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_ActionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_ActionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest.class, Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest.Builder.class);
    }

    public static final int ACTION_FIELD_NUMBER = 1;
    private int action_;
    /**
     * <code>.simulation.Action action = 1;</code>
     */
    public int getActionValue() {
      return action_;
    }
    /**
     * <code>.simulation.Action action = 1;</code>
     */
    public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Action getAction() {
      @SuppressWarnings("deprecation")
      Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Action result = Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Action.valueOf(action_);
      return result == null ? Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Action.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (action_ != Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Action.Nothing.getNumber()) {
        output.writeEnum(1, action_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (action_ != Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Action.Nothing.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, action_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest)) {
        return super.equals(obj);
      }
      Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest other = (Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest) obj;

      boolean result = true;
      result = result && action_ == other.action_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + action_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code simulation.ActionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:simulation.ActionRequest)
        Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_ActionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_ActionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest.class, Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest.Builder.class);
      }

      // Construct using Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        action_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_ActionRequest_descriptor;
      }

      @java.lang.Override
      public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest getDefaultInstanceForType() {
        return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest build() {
        Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest buildPartial() {
        Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest result = new Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest(this);
        result.action_ = action_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest) {
          return mergeFrom((Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest other) {
        if (other == Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest.getDefaultInstance()) return this;
        if (other.action_ != 0) {
          setActionValue(other.getActionValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int action_ = 0;
      /**
       * <code>.simulation.Action action = 1;</code>
       */
      public int getActionValue() {
        return action_;
      }
      /**
       * <code>.simulation.Action action = 1;</code>
       */
      public Builder setActionValue(int value) {
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.simulation.Action action = 1;</code>
       */
      public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Action getAction() {
        @SuppressWarnings("deprecation")
        Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Action result = Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Action.valueOf(action_);
        return result == null ? Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Action.UNRECOGNIZED : result;
      }
      /**
       * <code>.simulation.Action action = 1;</code>
       */
      public Builder setAction(Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Action value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        action_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.simulation.Action action = 1;</code>
       */
      public Builder clearAction() {
        
        action_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:simulation.ActionRequest)
    }

    // @@protoc_insertion_point(class_scope:simulation.ActionRequest)
    private static final Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest();
    }

    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ActionRequest>
        PARSER = new com.google.protobuf.AbstractParser<ActionRequest>() {
      @java.lang.Override
      public ActionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ActionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ActionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.ActionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:simulation.Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code simulation.Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:simulation.Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty.class, Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty)) {
        return super.equals(obj);
      }
      Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty other = (Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code simulation.Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:simulation.Empty)
        Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty.class, Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty.Builder.class);
      }

      // Construct using Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.internal_static_simulation_Empty_descriptor;
      }

      @java.lang.Override
      public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty getDefaultInstanceForType() {
        return Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty build() {
        Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty buildPartial() {
        Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty result = new Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty) {
          return mergeFrom((Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty other) {
        if (other == Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:simulation.Empty)
    }

    // @@protoc_insertion_point(class_scope:simulation.Empty)
    private static final Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty();
    }

    public static Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Axxes.SkiSimulation.Algorithms.JavaGrpc.Simulation.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_simulation_ViewportReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_simulation_ViewportReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_simulation_ActionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_simulation_ActionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_simulation_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_simulation_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020simulation.proto\022\nsimulation\"\037\n\rViewpo" +
      "rtReply\022\016\n\006matrix\030\001 \001(\t\"3\n\rActionRequest" +
      "\022\"\n\006action\030\001 \001(\0162\022.simulation.Action\"\007\n\005" +
      "Empty**\n\006Action\022\013\n\007Nothing\020\000\022\010\n\004Left\020\001\022\t" +
      "\n\005Right\020\0022\233\001\n\020EngineManagement\022@\n\020StartS" +
      "timulation\022\021.simulation.Empty\032\031.simulati" +
      "on.ViewportReply\022E\n\rPerformAction\022\031.simu" +
      "lation.ActionRequest\032\031.simulation.Viewpo" +
      "rtReplyB)\n\'Axxes.SkiSimulation.Algorithm" +
      "s.JavaGrpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_simulation_ViewportReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_simulation_ViewportReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_simulation_ViewportReply_descriptor,
        new java.lang.String[] { "Matrix", });
    internal_static_simulation_ActionRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_simulation_ActionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_simulation_ActionRequest_descriptor,
        new java.lang.String[] { "Action", });
    internal_static_simulation_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_simulation_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_simulation_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
