name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    stage: build
    script:
      - docker build -f ./csharp/build.Dockerfile .
    only:
      - merge_requests
      - pushes
