image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - build

build:
  stage: build
  script:
    - docker build -f ./build.Dockerfile .
  only:
    - merge_requests
    - pushes
